/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.worldbankia;

import java.awt.Color;

/**
 *
 * @author twumn
 */
public class ChartType extends javax.swing.JFrame {

    /**
     * Creates new form ChartType
     */
    public ChartType() {
        initComponents();
    }

    ChartType(Dashboard aThis) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        DL1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        DL2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        DL3 = new javax.swing.JLabel();

        DL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        DL.setForeground(new java.awt.Color(119, 129, 149));
        DL.setText("   Dashboard");
        DL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DLMouseExited(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        DL1.setBackground(new java.awt.Color(0, 0, 0));
        DL1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        DL1.setForeground(new java.awt.Color(51, 0, 0));
        DL1.setText("Select Chart Type");
        DL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DL1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DL1MouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(29, 43, 75));

        DL2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        DL2.setForeground(new java.awt.Color(119, 129, 149));
        DL2.setText("Bar Chart");
        DL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DL2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DL2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DL2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(DL2)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DL2)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(29, 43, 75));

        DL3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        DL3.setForeground(new java.awt.Color(119, 129, 149));
        DL3.setText("Line Chart");
        DL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DL3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DL3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DL3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(DL3)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DL3)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DL1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DL1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DL1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DL1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DL1MouseEntered

    private void DL1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DL1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_DL1MouseExited

    private void DLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DLMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DLMouseClicked

    private void DLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DLMouseEntered
        DL.setForeground(Color.WHITE);
      
    }//GEN-LAST:event_DLMouseEntered

    private void DLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DLMouseExited

    }//GEN-LAST:event_DLMouseExited

    private void DL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DL2MouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_DL2MouseClicked

    private void DL2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DL2MouseEntered
        DL.setForeground(Color.WHITE);
     
    }//GEN-LAST:event_DL2MouseEntered

    private void DL2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DL2MouseExited
   
    }//GEN-LAST:event_DL2MouseExited

    private void DL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DL3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DL3MouseClicked

    private void DL3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DL3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DL3MouseEntered

    private void DL3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DL3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_DL3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChartType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChartType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChartType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChartType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChartType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DL;
    private javax.swing.JLabel DL1;
    private javax.swing.JLabel DL2;
    private javax.swing.JLabel DL3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
